---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .Values.redis.fullnameOverride }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
addressType: FQDN
ports:
  - name: redis
    protocol: TCP
    port: 6379
endpoints:
  - addresses:
      - >-
        redis-0.svc.cluster.local
    conditions:
      ready: true
    hostname: redis-0
    nodeName: k8s10.breeze-blocks.net

