---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    name: redis
    volume.kubernetes.io/name: redis
    volume.kubernetes.io/storage-provisioner: {{ .Values.redis.persistence.storageClass }}
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
  name: redis
  namespace: redis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: usb
  volumeMode: Filesystem
