allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: manual
mountOptions:
- discard # this might enable UNMAP / TRIM at the block storage layer
parameters:
  guaranteedReadWriteLatency: "true" # provider-specific
provisioner: local
reclaimPolicy: Delete # default value is Delete
