{{ if eq .Values.type "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Values.fullnameOverride }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "redis.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{ .Values.nodeSelector | toYaml | nindent 8 }}
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: redis
          volumeMounts:
            - name: {{ .Values.persistence.name }}
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.persistence.name }}
    spec:
      accessModes:
        - ReadWriteMany
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.resources.requests.storage }}
      storageClassName: {{ .Values.persistence.storageClass }}
      volumeMode: Filesystem
{{ end }}
